services:
#    kmda.example:
#        class: kmdaBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    kmda.cech_voter:
        class: kmdaBundle\Security\cechVoter
        tags:
            - { name: security.voter }
        # small performance boost
#        public: false