kmdaBundle\Entity\BuildingPurpose:
    type: entity
    table: building_purpose
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: true
            length: 160
            fixed: false
    lifecycleCallbacks: {  }
