kmdaBundle\Entity\DepartmentSubord:
    type: entity
    table: department_subord
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
