kmdaBundle\Entity\KyivDistrict:
    type: entity
    table: kyiv_district
#    indexes:
#        IDX_31C15487A67B1E36:
#            columns:
#                - id_city
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: 'Назва району мiста'
    lifecycleCallbacks: {  }
