kmdaBundle\Entity\OrgOccupation:
    type: entity
    table: org_occupation
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: true
            length: 50
            fixed: false
    lifecycleCallbacks: {  }
