kmdaBundle\Entity\Phonenumber:
    type: entity
    table: Phonenumber
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255

    lifecycleCallbacks: {  }
