<?php

namespace kmdaBundle\Repository;

/**
 * BalanceObjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BalanceObjectRepository extends \Doctrine\ORM\EntityRepository
{
}
