<?php

namespace kmdaBundle\Repository;

/**
 * OrendaDocRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrendaDocRepository extends \Doctrine\ORM\EntityRepository
{
}
