<?php

namespace kmdaBundle\Repository;

/**
 * OrendaReshRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrendaReshRepository extends \Doctrine\ORM\EntityRepository
{
}
