<?php

namespace kmdaBundle\Repository;

/**
 * Street_TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Street_TypeRepository extends \Doctrine\ORM\EntityRepository
{
}
