<?php

namespace kmdaBundle\Repository;

/**
 * VotingDtpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VotingDtpRepository extends \Doctrine\ORM\EntityRepository
{
	public function votingResultAll(){

		$emTrue = $this->createQueryBuilder('voting');
		$emTrue	->select('voting.idTicketit',"count('voting.idTicketit') as yes")
				->where("voting.voice = 't'")
		        ->groupBy('voting.idTicketit');

		//$emTrue->expr()->count()
		$yes = $emTrue->getQuery()->getResult();

		$emTrue = $this->createQueryBuilder('voting');
		$emTrue	->select('voting.idTicketit',"count('voting.idTicketit') as no")
			->where("voting.voice = 'f'")
			->groupBy('voting.idTicketit');

		//$emTrue->expr()->count()
		$no = $emTrue->getQuery()->getResult();

		foreach($no as $k1=>$v1){
			$i = 0;
			foreach($yes as $k2=>$v2){
				if($v1["idTicketit"] == $v2["idTicketit"]){
					$i = 1;
				}
			}
			if($i == 0){
				$v1['yes'] = 0;
				array_push($yes, $v1);
			}
		}
		foreach($yes as $k1=>&$v1){
			foreach($no as $k2=>$v2){
			 if(($v1["idTicketit"] == $v2["idTicketit"])  && (!isset($v1["no"]))){
				 $v1['no'] = $v2['no'];
			 }
			}
			if(!isset($v1['no'])){
				$v1['no'] = 0;
			}
		}

		return $yes;

	}

}

