house_index:
    path:     /
    defaults: { _controller: "kmdaBundle:House:index" }
    methods:  GET

house_show:
    path:     /{id}/show
    defaults: { _controller: "kmdaBundle:House:show" }
    methods:  GET

house_new:
    path:     /new
    defaults: { _controller: "kmdaBundle:House:new" }
    methods:  [GET, POST]

house_edit:
    path:     /{id}/edit
    defaults: { _controller: "kmdaBundle:House:edit" }
    methods:  [GET, POST]

house_delete:
    path:     /{id}/delete
    defaults: { _controller: "kmdaBundle:House:delete" }
    methods:  DELETE
